@startuml
package "com.nutrimeal.nutrimeal" {
    package "controller" {
        package "manager"
    }
    package "service" {
    }
    package "model" {
    }
    package "config" {
        package "security" {
        }
    }

    package "repository" {
    }
}
@enduml