@startuml
package "Config" {
}

package "Controller" {
}

package "DTO" {
}

package "Email" {
}

package "Model" {
}

package "Repository" {
}

package "Service" {
}

package "Templates" {
}

Controller --> Service
Controller --> Templates
Service --> Repository
Service --> Model
Service --> DTO
Service --> Email
Repository --> Model
@enduml