@startuml
class Shipper {
}

class ShipperDashboard {
  +getOrdersBeingDelivered(): void
}

class ShipperController {
  +getOrdersByStatus(status: String): List<Order>
}

class ShipperService {
  +findOrdersByStatus(status: String): List<Order>
}

class ShipperRepository {
  +findOrdersByStatus(status: String): List<Order>
}

class Database {
}

Shipper --> ShipperDashboard : uses
ShipperDashboard --> ShipperController : interacts with
ShipperController --> ShipperService : interacts with
ShipperService --> ShipperRepository : interacts with
ShipperRepository --> Database : interacts with
@enduml
