@startuml

actor User
participant HomeController
participant ComboService
participant ComboRepository
database "Database" as Database

User -> HomeController: Request to view home page
activate HomeController
HomeController -> ComboService: getCombos()
activate ComboService
ComboService -> ComboRepository: findAllCombos()
activate ComboRepository
ComboRepository -> Database: SELECT * FROM Combo
activate Database
Database --> ComboRepository: Result set
deactivate Database
ComboRepository --> ComboService: List<Combos>
deactivate ComboRepository
ComboService --> HomeController: List<Combos>
deactivate ComboService
HomeController -> User: Render home page with combos
deactivate HomeController

@enduml
