@startuml

actor User

participant Browser
participant HomeController
participant ComboService
participant ComboRepository
database "Database" as Database

User -> Browser: Request to view combo detail
activate Browser
Browser -> HomeController: HTTP GET /combo/{id}
activate HomeController
HomeController -> ComboService: getComboById(id)
activate ComboService
ComboService -> ComboRepository: findComboById(id)
activate ComboRepository
ComboRepository -> Database: SELECT * FROM Combo WHERE id = ?
activate Database
Database --> ComboRepository: Result set
deactivate Database
ComboRepository --> ComboService: Combo
deactivate ComboRepository
ComboService --> HomeController: Combo
deactivate ComboService
HomeController -> Browser: Render combo detail page with combo
deactivate HomeController
Browser -> User: Display combo detail page with combo
deactivate Browser

@enduml
