@startuml

actor User

participant HomeController
participant ComboService
participant ComboRepository
database "Database" as Database

User -> HomeController: Request to view combo detail
activate HomeController
HomeController -> ComboService: getComboById(id)
activate ComboService
ComboService -> ComboRepository: findComboById(id)
activate ComboRepository
ComboRepository -> Database: SELECT * FROM Combo WHERE id = ?
activate Database
Database --> ComboRepository: Result set
deactivate Database
ComboRepository --> ComboService: Combo
deactivate ComboRepository
ComboService --> HomeController: Combo
deactivate ComboService
HomeController -> User: Render combo detail page with combo
deactivate HomeController

@enduml
