@startuml

actor User
participant "Browser" as Browser
participant "HomeController" as HomeController

User -> Browser: Request to view FAQs page
activate Browser
Browser -> HomeController: HTTP GET /faqs
activate HomeController
HomeController -> Browser: Render FAQs page
deactivate HomeController
Browser -> User: Display FAQs page
deactivate Browser

@enduml